#!/bin/sh

# Set this to your user name, the name on your secret key
PGPUSER=webmaster@hoohoo.ncsa.uiuc.edu
# Set this to the key to your secret key
PGPPASS=mypassword
# Set this to wherever you keep your secret and public keys
PGPPATH=/X11/robm/httpd/support/auth/pgp-keys
# Set this to the location of the PGP binary on your system
PGPBIN=/usr/local/bin/pgp

# You shouldn't need to edit anything under this line

export PGPPASS
export PGPPATH

# Make sure PGP doesn't try to make temp files in /
cd /tmp
exec $PGPBIN -fe $* -u $PGPUSER 2>/dev/null

