#!/bin/sh

# Set this to the location of uuencode on your system. If your system doesn't
# come with uuencode, use the one I have provided.
UUENCODE=/bin/uuencode
# Set this to the directory you are keeping your users' public keys in.
# You should keep each user's public key in a file in this directory, and the
# filename should be that user's entity name.
KEYS=/X11/robm/httpd/support/auth/ripem-keys
# Set this to your server's entity name
# Be sure you place your server's public key into this user's .plan so that 
# the clients can find it.
PEMUSER=webmaster@hoohoo.ncsa.uiuc.edu
# Set this to the location of your secret key
SECKEY=/X11/robm/httpd/htauth/.key-private
# Set this to the password to your secret key
KEYPASS=mypassword
# Set this to the location of your RIPEM executable
RIPEMBIN=/usr/local/bin/ripem

$UUENCODE foo | $RIPEMBIN -e -h i -Y f -p $KEYS/"$*" -u $PEMUSER -s $SECKEY -k $KEYPASS -r $*




